In [33]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [34]:
df = pd.read_csv("/Users/mdbarshay/Desktop/401/Project 3/final.csv", index_col = 0)

In [35]:
df

,num_room,full_sq,sport_count_5000,sport_count_3000,trc_count_5000,zd_vokzaly_avto_km,sadovoe_km,sport_count_2000,kremlin_km,bulvar_ring_km,...,exhibition_km,big_church_count_5000,sport_count_1000,office_sqm_1500,market_count_5000,school_education_centers_raion,museum_km,healthcare_centers_raion,big_church_km,price_doc
0,1.962264,43,52,21,52,14.231961,13.100618,10,15.156211,13.675657,...,7.023705,13,6,39554,4,5,7.389498,1,0.625783,5850000
1,1.925926,34,66,19,40,9.242586,6.444333,11,8.698054,8.132640,...,2.358840,15,2,102910,14,8,0.709260,1,0.967821,6000000
2,1.858586,43,67,20,35,9.540544,6.963403,8,9.067885,8.054252,...,4.958214,11,5,0,10,7,3.156423,1,3.178751,5700000
3,2.132275,89,26,18,22,17.478380,17.457198,13,19.487005,18.309433,...,5.029696,4,3,11000,3,10,16.041521,1,1.031777,13100000
4,2.875000,77,195,77,114,1.595898,0.046810,21,2.578671,0.787593,...,1.339652,135,7,1195735,14,9,1.800125,4,0.378756,16331452
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30287,2.000000,44,84,29,53,11.396447,10.543724,15,12.599292,11.118577,...,4.877876,15,3,217042,6,4,4.836787,1,1.235066,7400000
30288,4.000000,86,171,80,90,1.010437,1.203215,36,3.269284,1.874868,...,3.543784,98,8,1815698,15,4,1.450108,3,0.850385,25000000
30289,1.000000,45,11,6,4,25.699461,19.868997,3,21.905792,21.038561,...,4.555385,2,0,0,1,0,9.890758,0,1.192543,6970959
30290,2.000000,64,65,33,45,15.303338,11.752036,18,13.622569,12.872535,...,1.800186,6,10,37800,7,8,4.119706,2,1.644053,13500000
30291,2.000000,43,54,26,22,12.243439,9.675169,12,11.812614,10.228634,...,2.477068,7,3,0,10,4,0.127867,2,0.480531,5600000

In [50]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [51]:
scaler_x = StandardScaler()

In [52]:
scaler_x.fit(X)

StandardScaler()

In [53]:
scaled_X = scaler_x.transform(X)

In [56]:
centered_y_per100k = (y/100000) - np.mean(y/100000)

In [58]:
centered_y_per100k

0        -12.979129
1        -11.479129
2        -14.479129
3         59.520871
4         91.835391
            ...
30287      2.520871
30288    178.520871
30289     -1.769539
30290     63.520871
30291    -15.479129
Name: price_doc, Length: 30292, dtype: float64

In [26]:
# y = np.array(y).reshape(-1,1)

In [27]:
scaler_y = StandardScaler()
scaler_y.fit(y)
scaled_y = scaler_y.transform(y)

In [29]:
scaled_X

array([[ 0.066649  , -0.29474787, -0.02396938, ...,  0.09597106,
        -0.22004101, -0.60448185],
       [ 0.0158866 , -0.53080661,  0.27873534, ..., -1.18386687,
        -0.22004101, -0.47575602],
       [-0.07818357, -0.29474787,  0.3003571 , ..., -0.71502551,
        -0.22004101,  0.35632877],
       ...,
       [-1.27757834, -0.24229037, -0.91046177, ...,  0.57517665,
        -0.88946776, -0.39118156],
       [ 0.1193638 ,  0.25605587,  0.25711357, ..., -0.53047418,
         0.44938575, -0.22125583],
       [ 0.1193638 , -0.29474787,  0.01927415, ..., -1.2952534 ,
         0.44938575, -0.65914774]])

In [30]:
scaled_y

array([[-0.27141117],
       [-0.24004414],
       [-0.3027782 ],
       ...,
       [-0.03700346],
       [ 1.32830742],
       [-0.32368955]])

In [59]:
pd.DataFrame(scaled_X).to_csv("/Users/mdbarshay/Desktop/401/Project 3/scaled_X.csv")
pd.DataFrame(centered_y_per100k).to_csv("/Users/mdbarshay/Desktop/401/Project 3/centered_y_per100k.csv")